name: holy_sheet
description: A Flutter sheet & panel widget that's good as hell.
version: 0.0.3
author: Matt Condon (shrugs) <matt@bydot.app>
homepage: https://github.com/XLNT/holy_sheet

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
